# Generated by Django 6.0.2 on 2026-02-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
