# Generated by Django 6.0.2 on 2026-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='event',
            field=models.CharField(choices=[('OTP_REQUESTED', 'OTP_REQUESTED'), ('OTP_VERIFIED', 'OTP_VERIFIED'), ('OTP_FAILED', 'OTP_FAILED'), ('OTP_LOCKED', 'OTP_LOCKED')], default='OTP_REQUESTED', max_length=20),
        ),
    ]
